Vagrant.configure("2") do |config|
  config.vm.box = "precise64"
  config.vm.provider "virtualbox" do |vb|
    vb.customize ["modifyvm", :id, "--ioapic", "on"]
    vb.customize ["modifyvm", :id, "--memory", "2048"]
    vb.customize ["modifyvm", :id, "--cpus", "2"]
  end
  config.vm.network "forwarded_port", guest: 80, host: 9080,
    auto_correct: true
  config.vm.network "private_network", ip: "192.168.101.101"
  config.vm.synced_folder "../", "/vagrant/disturbometer-hack"
  config.ssh.forward_x11 = true
  config.ssh.forward_agent = true
  config.vm.hostname = "disturbometer-hack"
  config.vm.provision "shell", path: "bootstrap.sh"
end
